# Documentation available at https://expeditor.chef.io/docs/getting-started/

# The name of the product keys for this product (from mixlib-install)
product_key:
  - chef-workstation

project:
  alias: chef-workstation-18

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-ws-notify

docker_images:
  - chefworkstation

github:
  # This deletes the GitHub PR branch after successfully merged into the release branch
  delete_branch_on_merge: true
  # allow bumping the minor release via label
  minor_bump_labels:
    - "Expeditor: Bump Version Minor"
  # allow bumping the major release via label
  major_bump_labels:
    - "Expeditor: Bump Version Major"
  # Which Github branches to build Omnibus releases from, and what versions
  # (as determined by the value in the VERSION file) those branches are responsible
  # for building.
  # TODO we need to stop maintaining a 0.18 branch before 2021
  release_branch:
    - master:
        version_constraint: 20.*
    - cw-18:
        version_constraint: 0.18.*

# https://expeditor.chef.io/docs/getting-started/subscriptions/#merge-actions
# The `merge_actions` key is a shortcut for the
# `pull_request_merged:<GITHUB_REPO>:<RELEASE_BRANCH>:*` subscription.
merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - trigger_pipeline:omnibus/release:
      ignore_labels:
        - "Expeditor: Skip Omnibus"
        - "Expeditor: Skip All"
      only_if: built_in:bump_version

pipelines:
  - verify:
      description: Pull Request validation tests
  - omnibus/release
  - omnibus/adhoc:
      definition: .expeditor/release.omnibus.yml
      env:
        - ADHOC: true
  - third-party-packages:
      description: post-release publishing of Workstation packages to third party distribution platforms

subscriptions:
  - workload: artifact_published:unstable:chef-workstation:{{version_constraint}}
    actions:
      - built_in:build_docker_image
  - workload: artifact_published:current:chef-workstation:{{version_constraint}}
    actions:
      - built_in:tag_docker_image
  - workload: artifact_published:stable:chef-workstation:{{version_constraint}}
    actions:
      - built_in:rollover_changelog
      - bash:.expeditor/update_dockerfile.sh
      - bash:.expeditor/publish-release-notes.sh
      - bash:.expeditor/purge-cdn.sh
      - bash:.expeditor/announce-release.sh
      - built_in:tag_docker_image
      # publish to third party package managers that have a dependency
      # on this artifact's availability
      - trigger_pipeline:third-party-packages
  - workload: artifact_published:stable:chef:15*
    actions:
      # update our pinned version for chef/chef-bin in Gemfile
      - bash:.expeditor/update_chef.sh
      # update gemfile.lock and make it a PR
      - bash:.expeditor/update_dep.sh
